include: "common.smk"


rule all:
    input:
        f="trimmed_R1.fastq.gz",
        r="trimmed_R2.fastq.gz",
    log:
        "log/qc-seq-all.txt",


rule cutadapt:
    input:
        f=config["forward"],
        r=config["reverse"],
    output:
        f="trimmed_R1.fastq.gz",
        r="trimmed_R2.fastq.gz",
    log:
        "log/cutadapt.txt",
    container:
        containers["cutadapt"]
    shell:
        """
        cutadapt -o {output.f} -p {output.r} \
            {input.f} {input.r} 2> {log}
        """
